# Generated by Django 6.0.7 on 2026-08-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0002_alter_patient_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
