# Generated by Django 6.1 on 2026-09-17 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medication', '0004_doctor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabin',
            fields=[
                ('cabin_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=32, unique=True)),
                ('cabin_type', models.CharField(max_length=64)),
                ('nightly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CabinApplication',
            fields=[
                ('application_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('reject_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('cabin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='cabins.cabin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabin_applications', to='medication.patient')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_cabin_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=32, unique=True)),
                ('nights', models.PositiveIntegerField()),
                ('nightly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, upload_to='invoices/')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='cabins.cabinapplication')),
            ],
        ),
    ]
